// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm-AHKpGhzcay3ZHf_4fDfNu_ff0CRDkE',
    appId: '1:343707523457:web:c154b8cc74ac228de2b080',
    messagingSenderId: '343707523457',
    projectId: 'pharamatracka',
    authDomain: 'pharamatracka.firebaseapp.com',
    storageBucket: 'pharamatracka.appspot.com',
    measurementId: 'G-BRN3D7BKC1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlMcPUUaShC8g2r9xZPoqaA2dEIKTPiYw',
    appId: '1:343707523457:android:4f3562b01d850a99e2b080',
    messagingSenderId: '343707523457',
    projectId: 'pharamatracka',
    storageBucket: 'pharamatracka.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMJTVRAemuCCH4LpyJQby28rjWI_8UnmY',
    appId: '1:343707523457:ios:2fbec691ca538f73e2b080',
    messagingSenderId: '343707523457',
    projectId: 'pharamatracka',
    storageBucket: 'pharamatracka.appspot.com',
    iosClientId: '343707523457-fri2kn48qfo52c56tl3gi6gcl8p0dt1m.apps.googleusercontent.com',
    iosBundleId: 'com.example.pharmTraka',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMJTVRAemuCCH4LpyJQby28rjWI_8UnmY',
    appId: '1:343707523457:ios:2fbec691ca538f73e2b080',
    messagingSenderId: '343707523457',
    projectId: 'pharamatracka',
    storageBucket: 'pharamatracka.appspot.com',
    iosClientId: '343707523457-fri2kn48qfo52c56tl3gi6gcl8p0dt1m.apps.googleusercontent.com',
    iosBundleId: 'com.example.pharmTraka',
  );
}
